### ISSUE TITLE
[TODO] Clipping Effect

### ISSUE THREAD

**Issue by andwn** [andwn/cave-story-md#167]
Erases one line at a time on the sprite, for teleportation mostly.

Checklist of places used
- [x] Player using teleporter
- [ ] Booster appearing from teleporter in Grasstown Shelter
- [ ] Misery appearing
- [ ] Misery summons Toroko and Sue
- [ ] Misery teleports Quote and Balrog away in Sand Zone
- [ ] The Doctor appearing and leaving before Toroko boss
- [ ] Misery teleports the Core away after defeating it
- [x] Pooh Black death animation
- [x] Muscle Doctor death animation

**Comment by andwn** [comment]
Well that's a feature I didn't know about
![chrome_2017-03-23_19-24-56](https://cloud.githubusercontent.com/assets/8164394/24274424/7741ae74-0ffe-11e7-950d-8169541ed99a.png)

**Comment by Leo40Git** [comment]
Misery uses a special "line split" animation when she teleports in her boss fight.
![miserytele](https://cloud.githubusercontent.com/assets/7997354/24359699/c6444272-130d-11e7-80c0-2824488228f7.png)
(this is using misery2's palette)

**Comment by andwn** [comment]
It's been a while since March 2017 I should probably add those Misery frames soon

**Comment by andwn** [comment]
Decided I really don't want to come up with a set of algorithms to do this and am going to flash visibility instead, with exceptions for some sprites (I feel like it is an important part of Pooh Black and Muscle Doctor death animations).

**Comment by SkyTheLeafeon** [comment]
OK.

**Comment by andwn** [comment]
With that last commit pooh black and muscle doctor have dissolve animations, and that's good enough for me
